import { useState } from 'react';
import { CheckCircle2, Loader2, Play, XCircle } from 'lucide-react';

type StepStatus = 'idle' | 'running' | 'done' | 'error';

interface PipelineStep {
  id: string;
  tool: string;
  description: string;
  output: string;
  duration: number;
  color: string;
}

const PIPELINE: PipelineStep[] = [
  {
    id: 'allowlist',
    tool: 'Allowlist check',
    description: 'Target URL is validated before any tool process can start.',
    output: 'Target http://localhost:8888 is allowlisted.',
    duration: 400,
    color: 'var(--green)',
  },
  {
    id: 'nmap',
    tool: 'Nmap discovery',
    description: 'Service discovery uses argument arrays and subprocess timeouts.',
    output: 'Open ports: 80/tcp, 443/tcp, 8080/tcp',
    duration: 900,
    color: 'var(--indigo)',
  },
  {
    id: 'zap',
    tool: 'OWASP ZAP',
    description: 'Web scan findings are normalized and persisted as artifacts.',
    output: '3 findings mapped: missing CSP, version header, cookie flag.',
    duration: 1300,
    color: 'var(--amber)',
  },
  {
    id: 'trivy',
    tool: 'Trivy optional',
    description: 'Image scanning only runs when the requested image is explicitly allowed.',
    output: 'Filesystem evidence can be generated by CI self-scan.',
    duration: 700,
    color: 'var(--violet)',
  },
  {
    id: 'persist',
    tool: 'Artifact persist',
    description: 'Tool outputs are stored and exposed through assessment artifact endpoints.',
    output: 'Assessment stored. Artifacts: nmap, zap, trivy. Status: completed.',
    duration: 350,
    color: 'var(--teal)',
  },
];

const initialStatuses = () => Object.fromEntries(PIPELINE.map((step) => [step.id, 'idle' as StepStatus]));

export function PipelineTrace() {
  const [statuses, setStatuses] = useState<Record<string, StepStatus>>(initialStatuses);
  const [running, setRunning] = useState(false);
  const [currentStep, setCurrentStep] = useState<string | null>(null);

  const runPipeline = async () => {
    if (running) return;
    setRunning(true);
    setStatuses(initialStatuses());

    for (const step of PIPELINE) {
      setCurrentStep(step.id);
      setStatuses((previous) => ({ ...previous, [step.id]: 'running' }));
      await new Promise((resolve) => setTimeout(resolve, step.duration));
      setStatuses((previous) => ({ ...previous, [step.id]: 'done' }));
    }

    setCurrentStep(null);
    setRunning(false);
  };

  const reset = () => {
    setStatuses(initialStatuses());
    setCurrentStep(null);
    setRunning(false);
  };

  return (
    <div className="pipeline-trace">
      <div className="pipeline-trace__actions">
        <button type="button" className="btn btn--primary" onClick={runPipeline} disabled={running}>
          {running ? <Loader2 size={15} className="spin" aria-hidden /> : <Play size={15} aria-hidden />}
          {running ? 'Running' : 'Run assessment'}
        </button>
        <button type="button" className="btn btn--ghost btn--sm" onClick={reset} disabled={running}>
          Reset
        </button>
      </div>

      <div className="pipeline-steps">
        {PIPELINE.map((step, index) => {
          const status = statuses[step.id];
          return (
            <div key={step.id} className={`pipeline-step pipeline-step--${status}`}>
              {index < PIPELINE.length - 1 ? (
                <div
                  className={`pipeline-step__line${
                    statuses[PIPELINE[index + 1].id] !== 'idle' ? ' pipeline-step__line--active' : ''
                  }`}
                  aria-hidden
                />
              ) : null}

              <div className="pipeline-step__node" style={{ borderColor: status !== 'idle' ? step.color : undefined }}>
                {status === 'running' ? <Loader2 size={14} className="spin" style={{ color: step.color }} aria-hidden /> : null}
                {status === 'done' ? <CheckCircle2 size={14} style={{ color: step.color }} aria-hidden /> : null}
                {status === 'error' ? <XCircle size={14} className="text-rose" aria-hidden /> : null}
                {status === 'idle' ? <span className="pipeline-step__num">{index + 1}</span> : null}
              </div>

              <div className="pipeline-step__body">
                <span className="pipeline-step__tool">{step.tool}</span>
                <span className="pipeline-step__desc">{step.description}</span>
                {status === 'done' ? <pre className="pipeline-step__output">{step.output}</pre> : null}
                {currentStep === step.id ? <span className="pipeline-step__running">Running tool step...</span> : null}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
